# Generated by Django 4.0.3 on 2023-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('post_date', models.DateTimeField()),
                ('author', models.CharField(default='', max_length=15)),
                ('content', models.CharField(default='', max_length=5000)),
                ('title_subhead_1', models.CharField(default='', max_length=50)),
                ('content_subhead_1', models.CharField(default='', max_length=5000)),
                ('title_subhead_2', models.CharField(default='', max_length=50)),
                ('content_subhead_2', models.CharField(default='', max_length=5000)),
                ('thumbnail', models.ImageField(default='', upload_to='Blog/images')),
                ('about', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
