# Generated by Django 4.0.3 on 2022-12-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=70)),
                ('Email', models.CharField(default='', max_length=80)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('Text', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=4000)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=80)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=80)),
                ('state', models.CharField(default='', max_length=80)),
                ('zip_code', models.CharField(default='', max_length=50)),
                ('Phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('time_stamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=30)),
                ('product_desc', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
