# Generated by Django 4.0.3 on 2022-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='abc',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='abc',
            name='state',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='abc',
            name='zip_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
