# Generated by Django 4.0.3 on 2023-01-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_abc_phone_abc_state_abc_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
