# Generated by Django 4.0.3 on 2023-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_abc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='amount',
            field=models.CharField(default='', max_length=41),
        ),
    ]
