# Generated by Django 4.0.3 on 2023-01-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_abc_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
